### ISSUE TITLE
Logging: Pipe logging of PDFreactor to console

### ISSUE THREAD

**Issue by alex3683** [aixigo/pdfreactor-loader#1]
Currently the logs written by PDFreactor are only visible at the end of the generated report. Additionally there should be an option to send the logs to [console](https://nodejs.org/dist/latest-v6.x/docs/api/console.html) or some configurable logging mechanism.

**Comment by jpommerening** [comment]
Apparently it is [possible](http://www.pdfreactor.com/product/doc/apidocs/com/realobjects/pdfreactor/Configuration.html#setLogger(java.util.logging.Logger)) to provide a [`Logger`](http://docs.oracle.com/javase/6/docs/api/java/util/logging/Logger.html?is-external=true) when configuring PDFreactor.

One would usually override the `log(LogRecord)` method to intercept the log output. I just wish there was an API expecting something implementing an interface instead of a subclass, because those are much easier to [integrate](https://github.com/joeferner/node-java#javaNewProxy) with the `java` (node) module…

**Comment by alex3683** [comment]
As just discussed in _real life_<sup>™️</sup>:
~~Let's add a Java class extending `Logger`, that takes a simple callback interface we can then proxy in JavaScript.~~
Let's add a Java class extending [`Handler`](http://docs.oracle.com/javase/6/docs/api/java/util/logging/Handler.html), that takes a simple callback interface we can then [proxy](https://github.com/joeferner/node-java#javaNewProxy) in JavaScript. We're then able to create a default logger adding our custom `Handler` instance to it.

**Comment by alex3683** [comment]
Implemented on `master` (`v0.3.0`).
